image: node

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests

//Add cache to make program run faster
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve & 
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://lp1test-staging.surge.sh 
  script:
    - npm install --global surge
    - surge --project ./public --domain lp1test-staging.surge.sh    

deploy production:
  stage: deploy production
  environment:
    name: production
    url: http://lp1test.surge.sh 
  script:
    - npm install --global surge
    - surge --project ./public --domain lp1test.surge.sh

production tests:
  image: alphine
  stage: production tests
  script:
    - apk add --no-cache curl
    - curl -s "https://lp1test.surge.sh" | grep "Hi people"

  